In [1]:
import tensorflow as tf

# Create a tensor of n-dimension

## the 4 main type of tensor are :
* tf.Variable
* tf.constant
* tf.placeholder
* tf.SparseTensor
#####  A tensor is an object with three proporties
* A unique label(name)
* A dimension (shape)
* A data type (dtype)

In [46]:
r1 = tf.constant(1, tf.int16)

In [47]:
print(r1)

Tensor("Const_3:0", shape=(), dtype=int16)


In [48]:
r2 = tf.constant(1, tf.int16, name ="my_scalar")

In [49]:
print(r2)

Tensor("my_scalar:0", shape=(), dtype=int16)


In [50]:
# Decimal
r1_decimal = tf.constant(1.12345, tf.float32)
print(r1_decimal)
# String
r1_string = tf.constant("Kirubel", tf.string)
print(r1_string)

Tensor("Const_4:0", shape=(), dtype=float32)
Tensor("Const_5:0", shape=(), dtype=string)


In [51]:
## Rank 1
r1_vector = tf.constant([1,3,5], tf.int16)
print(r1_vector)
r2_boolean = tf.constant([True, True, False], tf.bool)
print(r2_boolean)
r2_boolean.shape

Tensor("Const_6:0", shape=(3,), dtype=int16)
Tensor("Const_7:0", shape=(3,), dtype=bool)


TensorShape([Dimension(3)])

In [52]:
## Rank 2
r2_matrix = tf.constant([[1,2],
                        [3,4]], tf.int16)
print(r2_matrix)
r2_matrix.shape

Tensor("Const_8:0", shape=(2, 2), dtype=int16)


TensorShape([Dimension(2), Dimension(2)])

In [53]:
## Rank 3 
r3_matrix = tf.constant([[[1,2],
                         [3,4],
                         [5,6]]], tf.int16)
print(r3_matrix)
r3_matrix.shape

Tensor("Const_9:0", shape=(1, 3, 2), dtype=int16)


TensorShape([Dimension(1), Dimension(3), Dimension(2)])

## Shape of Tensor

In [54]:
# Shape of tensor
m_shape = tf.constant([[10,11],
                      [12, 13],
                      [14, 15]])
m_shape.shape

TensorShape([Dimension(3), Dimension(2)])

In [55]:
# Create a vector of 0
print(tf.zeros(10))

Tensor("zeros:0", shape=(10,), dtype=float32)


In [56]:
# Create a vector of ones with the same number of rows as m_shape
print(tf.ones(m_shape.shape[0]))

Tensor("ones:0", shape=(3,), dtype=float32)


In [57]:
# Create a vector of ones with the same number of column as m_shape
print(tf.ones(m_shape.shape[1]))

Tensor("ones_1:0", shape=(2,), dtype=float32)


In [58]:
print(tf.ones(m_shape.shape))

Tensor("ones_2:0", shape=(3, 2), dtype=float32)


## Type of data

In [59]:
print(m_shape.dtype)

<dtype: 'int32'>


In [60]:
# change type of data in tensor
# Note a tensor can only have one data type at a time
# TensorFlow chooses the type of data automatically when
#the argument is not specified during the creation of
#the tensor.
type_float = tf.constant(3.123456789, tf.float32)
type_int = tf.cast(type_float, dtype=tf.int32)
print(type_float.dtype)
print(type_int.dtype)

<dtype: 'float32'>
<dtype: 'int32'>


## creating operator

In [64]:
x = tf.constant([2.0], dtype= tf.float32)
print(tf.sqrt(x))

Tensor("Sqrt:0", shape=(1,), dtype=float32)


commonly used operations 
* tf.add(a,b)
* tf.substract(a,b)
* tf.multiply(a,b)
* tf.div(a,b)
* tf.pow(a,b)
* tf.exp(a)
* tf.sqrt(a)

In [65]:
# add 
tensor_a = tf.constant([[1,2]], dtype=tf.int32)
tensor_b = tf.constant([[3, 4]], dtype=tf.int32)

tensor_add = tf.add(tensor_a, tensor_b)
print(tensor_add)

Tensor("Add:0", shape=(1, 2), dtype=int32)


In [66]:
# Multiply
tensor_multiply = tf.multiply(tensor_a, tensor_b)
print(tensor_multiply)

Tensor("Mul_1:0", shape=(1, 2), dtype=int32)


### Variables

##### Varibales represent a node where the values always change

In [82]:
# Create a Variable
## we use tf.get_variable() method
# clearing computational graph
tf.reset_default_graph()
var = tf.get_variable("var", [1,2] )#, reuse=True) #, shape=test.shape)
print(var.shape)

(1, 2)


In [83]:
var_init_1 = tf.get_variable("var_init_1", [1,2], dtype=tf.int32, initializer=tf.zeros_initializer)
print(var_init_1.shape)

(1, 2)


In [84]:
# Create a 2x2 
# tf.reset_default_graph()
matrixtensor_const = tf.constant([[10,20],[30,40]])
var_init_2 = tf.get_variable("var_init_2", dtype=tf.int32, initializer=matrixtensor_const)
print(var_init_2.shape)

(2, 2)


## Placeholder

Placeholder is used to initialize the data to flow inside the tensors. To supply a placeholder, you need to use the method feed_dict.The placeholder will be fed only within a session.

In [85]:
data_placeholder_a = tf.placeholder(tf.float32, name='data_placeholder_a')
print(data_placeholder_a)

Tensor("data_placeholder_a:0", dtype=float32)


# Session
TensorFlow works around 3 main components:
* Graph
* Tensor
* Session

`NOTE` session will excute the operation from the graph. To feed the graph with the values of a tensor, you need to open a session. Inside a session, you mut run an operator to create an output.

`Step 1` creat two tensors x and y

In [86]:
## Create, run and evalue a session
x = tf.constant([2])
y = tf.constant([4])


`Step 2` create the operator by multiplying x and y

In [87]:
## Create operator
multiply = tf.multiply(x, y)

`Step 3` Open a session. Perform all computations and close the session

In [88]:
## Create a session to run the code
sess = tf.Session() # open a session
result_1 = sess.run(multiply) # execute the operation
print(result_1)
sess.close() # close the session

[8]


In [89]:
# Create a session inside a block
with tf.Session() as sess:
    result_2 = multiply.eval() # eval is equivalent to run()
    # only used with in a constext of the session
    print(result_2)

[8]


In [92]:
## Check the tensors create before
# sess = tf.Session()
# print(sess.run(r1))
# print(sess.run(r2_matrix))
# print(sess.run(r3_matrix))

In [91]:
# calling to initialize the values of a varible
sess.run(tf.global_variables_initializer())
# the object will explicitly initialize all the variables
print(sess.run(var))
print(sess.run(var_init_1))
print(sess.run(var_init_2))

[[ 0.6680163 -1.0254891]]
[[0 0]]
[[10 20]
 [30 40]]


In [95]:
import numpy as np
power_a = tf.pow(data_placeholder_a, 2) # create the ops
with tf.Session() as sess:
    data = np.random.rand(1,10) # create a random array of data
    # feed the placeholder with data
    print(sess.run(power_a, feed_dict ={data_placeholder_a: data})) 

[[5.4759526e-01 2.7320078e-01 3.5285261e-01 9.7473913e-01 6.1963934e-01
  9.3337725e-04 2.5356822e-03 2.9165095e-01 3.9756921e-01 5.7222143e-02]]


# Graph
`Note` that the graph does not display the output of the operations, it only helps to visualize the connection between individual operations.

In [97]:
# f(x,z) = xz + x^2 + z + 5
x = tf.get_variable("x", dtype=tf.int32, initializer=tf.constant([5]))
z = tf.get_variable("z", dtype=tf.int32, initializer=tf.constant([6]))
c = tf.constant([5], name="constant")
square = tf.constant([2], name="square")
f = tf.multiply(x,z) + tf.pow(x,square) + z +c

In [98]:
init = tf.global_variables_initializer() # prepare to initialize all the variables
with tf.Session() as sess:
    init.run() # initialize x and y
    function_result = f.eval()
    print(function_result)

[66]
